api_version = "unstable"

[[extensions]]
handle = "discounts-allocator-js"
name = "t:name"
description = "t:description"
type = "function"

  [[extensions.targeting]]
  target = "purchase.discounts-allocator.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

# [START discounts-allocator.toml-configuration]
  [extensions.ui.paths]
  create = "/"
  details = "/app/discounts-allocator/:functionId"
# [END discounts-allocator.toml-configuration]
