# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b041a09aeb198519ee11704abec7f0c4"
name = "discount-function-examples"
handle = "discount-function-examples-1"
application_url = "https://advert-near-selection-downtown.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3a22a586.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://advert-near-selection-downtown.trycloudflare.com/auth/callback",
  "https://advert-near-selection-downtown.trycloudflare.com/auth/shopify/callback",
  "https://advert-near-selection-downtown.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
