# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "extensions-spin-app-1p-app-key"
name = "Extensions Spin App"
handle = "extensions-spin-app"
application_url = "https://extensions.discount-functions-testing-f0u7.shahriar-rahman.us.spin.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://extensions.discount-functions-testing-f0u7.shahriar-rahman.us.spin.dev/auth/shopify/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
