[package]
name = "discounts-allocator-rust"
version = "1.0.0"
edition = "2021"
rust-version = "1.74"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shopify_function = "0.5"
graphql_client = "0.13"

[profile.release]
lto = true
opt-level = 'z'
strip = true
